export const fakePoints = [
  {
    latitude: -26.329177 + 0.001,
    longitude: -48.811036 + 0.001,
    tipo: 'Tipo 1',
    status: 'Status 1',
    cliente: 'Cliente 1',
    cidade: 'Cidade 1',
    subRegiao: 'Sub-região 1',
    dispositivo: 'Dispositivo 1',
    utilizador: 'Utilizador 1',
    altitude: 100,
    acuracia: 1,
    dataCriacao: new Date(),
    dataTransmissao: new Date(),
    dataModificacao: new Date(),
    observacao: 'Observação 1',
    distancia: 1,
    imagem: 'URL da imagem 1',
  },
  {
    latitude: -26.329177 - 0.001,
    longitude: -48.811036 - 0.001,
    tipo: 'Tipo 2',
    status: 'Status 2',
    cliente: 'Cliente 2',
    cidade: 'Cidade 2',
    subRegiao: 'Sub-região 2',
    dispositivo: 'Dispositivo 2',
    utilizador: 'Utilizador 2',
    altitude: 200,
    acuracia: 2,
    dataCriacao: new Date(),
    dataTransmissao: new Date(),
    dataModificacao: new Date(),
    observacao: 'Observação 2',
    distancia: 2,
    imagem: 'URL da imagem 2',
  },
  {
    latitude: -26.329177 + 0.002,
    longitude: -48.811036 + 0.002,
    tipo: 'Tipo 3',
    status: 'Status 3',
    cliente: 'Cliente 3',
    cidade: 'Cidade 3',
    subRegiao: 'Sub-região 3',
    dispositivo: 'Dispositivo 3',
    utilizador: 'Utilizador 3',
    altitude: 300,
    acuracia: 3,
    dataCriacao: new Date(),
    dataTransmissao: new Date(),
    dataModificacao: new Date(),
    observacao: 'Observação 3',
    distancia: 3,
    imagem: 'URL da imagem 3',
  },
  {
    latitude: -26.3290854,
    longitude: -48.810933299999995,
    tipo: 'Tipo 4',
    status: 'Status 4',
    cliente: 'Cliente 4',
    cidade: 'Cidade 4',
    subRegiao: 'Sub-região 4',
    dispositivo: 'Dispositivo 4',
    utilizador: 'Utilizador 4',
    altitude: 400,
    acuracia: 4,
    dataCriacao: new Date(),
    dataTransmissao: new Date(),
    dataModificacao: new Date(),
    observacao: 'Observação 4',
    distancia: 4,
    imagem: 'URL da imagem 4',
  },
  {
    latitude: -26.3292564,
    longitude: -48.8111455,
    tipo: 'Tipo 5',
    status: 'Status 5',
    cliente: 'Cliente 5',
    cidade: 'Cidade 5',
    subRegiao: 'Sub-região 5',
    dispositivo: 'Dispositivo 5',
    utilizador: 'Utilizador 5',
    altitude: 500,
    acuracia: 5,
    dataCriacao: new Date(),
    dataTransmissao: new Date(),
    dataModificacao: new Date(),
    observacao: 'Observação 5',
    distancia: 5,
    imagem: 'URL da imagem 5',
  },
]

export const difFakePoint = {
  latitude: -26.329177 - 0.002,
  longitude: -48.811036 - 0.002,
  tipo: 'Tipo FAKE',
  status: 'Status FAKE',
  cliente: 'Cliente FAKE',
  cidade: 'Cidade FAKE',
  subRegiao: 'Sub-região FAKE',
  dispositivo: 'Dispositivo FAKE',
  utilizador: 'Utilizador FAKE',
  altitude: 600,
  acuracia: 6,
  dataCriacao: new Date(),
  dataTransmissao: new Date(),
  dataModificacao: new Date(),
  observacao: 'Observação FAKE',
  distancia: 6,
  imagem: 'URL da imagem FAKE',
}
